name: CI

on:
  push:
    branches:
      - main  # ajuste conforme a sua branch principal
  pull_request:
    branches:
      - main  # ajuste conforme a sua branch principal

jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # ajuste conforme a versão do Node.js que você está utilizando

    - name: Instalar Dependências
      run: npm install

    - name: Executar Testes
      run: npm test
